/*
 * This source file was generated by the Gradle 'init' task
 */

public class App {
    public static void main(String[] args) {
        FuncionariosRepositorio repo = new FuncionariosRepositorio();

        Funcionario func = repo.randomFuncionario();
        Vendedor vendedor = repo.randomVendedor();

        System.out.println(vendedor);
    }
}
